import { readdirSync, statSync, existsSync, writeFileSync } from 'fs';
import { resolve } from 'path';
import { config } from '../config.js';
import type { ToolDefinition } from '../types.js';

async function generateDocsHandler(args: Record<string, unknown>): Promise<string> {
  const projectDir = (args['project'] as string)?.trim() || '.';
  const fullRoot = resolve(config.workspaceRoot, projectDir);

  if (!existsSync(fullRoot)) {
    return `❌ Project directory "${projectDir}" does not exist.`;
  }

  const entries = readdirSync(fullRoot);
  const fileTree: string[] = [];

  for (const item of entries) {
    if (item === 'node_modules' || item === '.git' || item === 'dist') continue;
    const itemPath = resolve(fullRoot, item);
    const isDir = statSync(itemPath).isDirectory();
    fileTree.push(`- \`${item}\` ${isDir ? '(Directory)' : '(File)'}`);
  }

  const readmeContent = `# ${projectDir.toUpperCase()}

> Autonomous documentation generated by **J.A.R.V.I.S. Engineering Agent**.

## Overview
This project is part of the JARVIS Workbench Suite.

## Project Structure
${fileTree.join('\n')}

## Getting Started
1. Open in browser: \`http://localhost:3000/projects/${projectDir}/index.html\`
2. Run tests or modify using JARVIS autonomous commands.

---
*Created at: ${new Date().toUTCString()}*
`;

  const readmePath = resolve(fullRoot, 'README.md');
  writeFileSync(readmePath, readmeContent, 'utf-8');

  return `✅ **Documentation Generated!** Created \`README.md\` in \`${projectDir}\`:\n\n` + readmeContent;
}

export const docsTools: ToolDefinition[] = [
  {
    name: 'generate_documentation',
    description: 'Autonomous documentation generator that creates complete README.md, architecture overview, and project summaries for any workbench project.',
    parameters: {
      type: 'object',
      properties: {
        project: {
          type: 'string',
          description: 'The project folder name in workbench/projects',
        },
      },
      required: ['project'],
    },
    execute: generateDocsHandler,
  },
];
